version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: language_helper
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
      build: .
      container_name: language-helper-app
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/language_helper
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: password
        SPRING_SQL_INIT_MODE: always
        # СЕКРЕТЫ ЧЕРЕЗ ПЕРЕМЕННЫЕ ОКРУЖЕНИЯ:
        API_KEY: ${API_KEY}
        JWT_SECRET: ${JWT_SECRET}
        SPRING_SECURITY_USER_PASSWORD: ${ADMIN_PASSWORD}
      ports:
        - "8080:8080"
      depends_on:
        db:
          condition: service_healthy

volumes:
  pgdata: