version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: language_helper
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d language_helper"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  app:
    build: .
    container_name: language-helper-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/language_helper
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_SQL_INIT_MODE: always
      API_KEY: ${API_KEY}
      JWT_SECRET: ${JWT_SECRET}
      SPRING_SECURITY_USER_PASSWORD: ${ADMIN_PASSWORD}
      # Разрешаем CORS для всех (для тестирования по IP)
      SPRING_APPLICATION_CORS_ALLOWED_ORIGINS: "*"
    # УБИРАЕМ порт 8080 - доступ только через фронтенд
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  frontend:
    build: ./frontend
    container_name: language-helper-frontend
    ports:
      - "80:80"  # ← СЛУШАЕМ НА ПОРТУ 80 (стандартный HTTP)
    environment:
      - VITE_API_URL=http://95.81.126.8/api  # ← УКАЖИТЕ ВАШ IP
    depends_on:
      - app
    restart: unless-stopped

volumes:
  pgdata: